name: 'Publish evidence to Platform'
description: "Capture job-level evidence data and publish it to the CloudBees platform."

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: false
    default: "https://api.cloudbees.io"
  cloudbees-pat:
    description: 'The CloudBees platform personal access token.'
    required: true
  content:
    description: 'The content to be published as evidence.'
    required: true
  format:
    description: 'The format of the evidence content.'
    required: false

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-publish-evidence-item:main-19d6ef14af635a51bcadff213f428b97a1cfb6e7" 
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    CLOUDBEES_API_TOKEN: ${{ inputs.cloudbees-pat }}
    CONTENT: ${{ inputs.content }}
