= Publish an evidence item to the CloudBees platform
 
Use this GitHub Action (GHA) to capture job-level evidence data in Markdown format in a GHA workflow run and publish it to the CloudBees platform.
The evidence is displayed on the *Evidence* tab of *Run details* for your run.
For more information, refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/evidence[the evidence documentation].

== Prequisites

Set up the CloudBees platform and GHA to work together, providing key features of the platform to GHA workflows.
Refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/gha-getting-started[Getting started with GHA integration] for more information.

== Inputs

[cols="22%a,15%a,15%a,48%a",options="header"]
.Input details
|===
| Input name
| Data type
| Required?
| Description

| `cloudbees-pat`
| String
| Yes
| The link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/personal-access-token[CloudBees platform personal access token].

| `content`
| String
| Yes
| The content to be published as evidence.

| `cloudbees-url`
| String
| No
| The CloudBees platform URL.
The default value is `"https://api.cloudbees.io"`.

|===

IMPORTANT: The required markup language format for the evidence content is link:https://www.markdownguide.org/basic-syntax/[Markdown].

== Usage examples
 
=== Basic example

The following is a basic example of using the action:

[source,yaml]
----
steps:
      - name: Publish evidence
        uses: cloudbees-gha-cbp/publish-evidence-item@v1
        with:
          cloudbees-pat: ${{ secrets.CBP_PAT }}
          content: |-
            # Sample Markdown evidence output
            - Application endpoint: https://app.example.com/qa
            - Artifacts
              - [backend.jar](https://example.com/repo/app/v1.0/backend.jar)

----

=== Full workflow and run example

The following GHA workflow example uses this action to publish evidence to the CloudBees platform.

.Example GHA workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
name: Output evidence

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: My evidence
        uses: cloudbees-gha-cbp/publish-evidence-item@v1
        id: go-action
        with :
          cloudbees-pat: ${{ secrets.CBP_PAT }}
          # content: "This is viewable on the Evidence tab of the run details."
----
--

After the run has completed, the evidence output is collected and displayed in the *Evidence* tab of *Run details*.

== License
 
This code is made available under the
link:https://opensource.org/license/mit/[MIT license].

== References
 
* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/intro[Using GitHub Actions with the CloudBees platform].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
 
